"""value

Revision ID: 3424134bdb38
Revises: fa1e613603cd
Create Date: 2026-03-29 14:04:54.584531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3424134bdb38'
down_revision: Union[str, None] = 'fa1e613603cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('value', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'value')
    # ### end Alembic commands ###
